-- ============================================================================
-- Seed: intentionally empty.
--
-- This file used to hold 54 Spanish universities and 18 UPV degrees. That list
-- was the signup blocker 0015_open_taxonomy.sql exists to remove: a student
-- outside it had to find an "other" escape hatch which then hid the degree
-- field entirely.
--
-- Institutions are now created on demand by find_or_create_institution() the
-- first time someone types a name, so the table fills itself with the
-- universities users actually attend rather than the ones we guessed. Degrees
-- are free text on profiles.degree_text and have no seed by construction.
--
-- Seeding anything here again would re-privilege one country's universities in
-- the fuzzy-search ranking, which is the thing we just removed.
--
-- The `degrees` table is NOT dropped — courses.degree_id still references it —
-- it is simply no longer part of signup.
-- ============================================================================
