import coreWebVitals from 'eslint-config-next/core-web-vitals';
import typescript from 'eslint-config-next/typescript';

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'supabase/.temp/**', // scratch files written by the local Supabase stack
      'supabase/.branches/**',
      '.gitnexus/**', // generated GitNexus index; git-ignored (its own .gitignore is `*`)
      'scripts/__fixtures__/**', // deliberate violations; see lint-tokens.test.ts
      'packages/contracts/src/db.ts', // generated by `supabase gen types`
      'messages/pseudo.json', // generated
    ],
  },
  ...coreWebVitals,
  ...typescript,
  {
    rules: {
      /*
       * CLAUDE.md: "No `any`. No `@ts-expect-error` without a linked issue."
       * Errors, not warnings — `pnpm lint` runs with --max-warnings 0, so a
       * warning would fail the build anyway but read as if it were optional.
       */
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/ban-ts-comment': [
        'error',
        { 'ts-expect-error': 'allow-with-description', minimumDescriptionLength: 10 },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
];

export default config;
